#!/bin/bash


pacman -Syu --noconfirm
pacman -S nginx --noconfirm
pacman -S ufw --noconfirm
useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen
mkdir /var/lib/webgen/bin
cp "$PWD/generate_index" /var/lib/webgen/bin/generate_index
mkdir /var/lib/webgen/HTML
chown -R webgen:webgen /var/lib/webgen
./generate_index
cp "$PWD/generate_index.service" /etc/systemd/system/generate-index.service
cp "$PWD/generate_index.timer" /etc/systemd/system/generate-index.timer
cp "$PWD/nginx.conf" /etc/nginx/nginx.conf
mkdir /etc/nginx/sites-available 
mkdir /etc/nginx/sites-enabled
cp "$PWD/system-info.conf" /etc/nginx/sites-available/system-info.conf
ln -s /etc/nginx/sites-available/system-info.conf /etc/nginx/sites-enabled/system-info.conf
systemctl enable --now nginx
systemctl enable --now ufw.service --noconfirm
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw limit ssh
ufw allow http
echo "y" | ufw enable


systemctl daemon-reload
echo "Installation complete. Web server running. Index file will be updated at 5am daily."

